### ISSUE TITLE
Could not find implicit value for evidence parameter of type 

### ISSUE THREAD

**Issue by AkhilNairAmey** [thurstonsand/scala-cass#36]
Hi,

I'm trying to run a select statement from the `README` and I'm hitting an error. I'm very new to scala, so I'm not certain what it means - is this something easily recifiable?

The whole error contains some other fluff as I'm compiling this as an R extension, but the root is this compile time error

```
error: could not find implicit value for evidence parameter of type com.weather.scalacass.CCCassFormatEncoder[Query]
    val selectRes: Iterator[Row] = sSession.select("mytable", Query("asdf", 123))
```

This is pretty much all the code I have which hits the compile error. 

```  
import com.weather.scalacass._
import com.datastax.driver.core.{ Cluster, Row }

object thing {

 implicit val cluster = Cluster.builder.addContactPoint("localhost").build()
  implicit val session = cluster.connect()

 val sSession = ScalaSession("spark")(session) // if mykeyspace already exists

 def test( a:Any* ) : Iterator[Row] = {
    // given the table and query definition
    case class MyTable(s: String, i: Int, l: Option[Long])
    case class Query(s: String, i: Int)

   val selectRes: Iterator[Row] = sSession.select("mytable", Query("asdf", 123), false, Option(1L))
  }

}
```

This package looks great btw, I hope I'll be able to use it!

Thanks very much,
Akhil

**Comment by thurstonsand** [comment]
hey Akhil. I'm not sure what it really means to define a case class inside a function, but I suspect that's your problem. Try this code block:
```scala
object thing {
  implicit val cluster = Cluster.builder.addContactPoint("localhost").build()
  implicit val session = cluster.connect()
  val sSession = ScalaSession("spark")(session) // if mykeyspace already exists

  case class MyTable(s: String, i: Int, l: Option[Long])
  case class Query(s: String, i: Int)
 def test( a:Any* ) : Iterator[Row] = sSession.select("mytable", Query("asdf", 123), false, Option(1L))
}
```
and let me know how it goes!

**Comment by thurstonsand** [comment]
oh and just so you know, you've sort of stumbled on a generic error regarding implicits that could mean a myriad of things...and the compiler won't tell you anything more specific than that. It's not the friendliest error to run into, and you're definitely not the only one to have run into it. But hopefully doing the above will resolve your problem

**Comment by AkhilNairAmey** [comment]
Thanks for the reply!  Gave it a shot and seemed to get a bit further.. I was prompted to add the `shapeless` package and remove the last two arguments from the `select` statement, but still hitting, what I'm assuming is a similar error:

 ```
import com.weather.scalacass._
import com.datastax.driver.core.{ Cluster, Row }

object thing {
  implicit val cluster = Cluster.builder.addContactPoint("localhost").build()
  implicit val session = cluster.connect()
  val sSession = ScalaSession("spark")(session) // if mykeyspace already exists

  case class MyTable(s: String, i: Int, l: Option[Long])
  case class Query(s: String, i: Int)
  def test( a:Any* ) : Iterator[Row] = sSession.select("mytable", Query("asdf", 123))
}
```

Resulting in error
```
error: polymorphic expression cannot be instantiated to expected type;
 found   : [S]com.weather.scalacass.scsession.SCSelectStatement[Iterator]
 required: Iterator[com.datastax.driver.core.Row]
  def test( a:Any* ) : Iterator[Row] = sSession.select("mytable", Query("asdf", 123))
```

I think at this point I'm running the readme exactly as expected so I'm not sure what's going on... Does a `mytable` table need to exist in cassandra?  FYI im using scala 2.11.8

Thanks again for your help

**Comment by thurstonsand** [comment]
oh yeah, that would do it. Sorry, that 2.0.0-M1 is not production ready, which is why I hadn't referenced it in the readme
