### ISSUE TITLE
When creating an insert statement, allow specifying ttl and consistency level parameters.

### ISSUE THREAD

**Issue by SajithaN** [thurstonsand/scala-cass#43]

**Comment by thurstonsand** [comment]
insert statements already allow TTL. write like
```scala
sSession.insert("mytable", MyCaseClass(myValue)).usingTTL(1234).execute()
```

could you clarify what you mean by consistency level? I don't see that in [the docs](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlInsert.html)

**Comment by SajithaN** [comment]
I am thinking about write consistency levels: https://docs.datastax.com/en/cassandra/3.0/cassandra/dml/dmlConfigConsistency.html#dmlConfigConsistency__dml-config-write-consistency

It can be set on PreparedStatement object.

`PreparedStatement setConsistencyLevel(ConsistencyLevel consistency)
Sets a default consistency level for all bound statements created from this prepared statement.
If no consistency level is set through this method, the bound statement created from this object will use the default consistency level (ONE).

Changing the default consistency level is not retroactive, it only applies to BoundStatement created after the change.

Parameters:
consistency - the default consistency level to set.
Returns:
this PreparedStatement object.`

https://docs.datastax.com/en/drivers/java/2.0/com/datastax/driver/core/PreparedStatement.html#setConsistencyLevel-com.datastax.driver.core.ConsistencyLevel-

**Comment by SajithaN** [comment]
It can also be on Batch level: 

`val batch = new BatchStatement(batchType)
    batch.setConsistencyLevel(consistencyLevel)`

**Comment by thurstonsand** [comment]
ah I understand. I'll look into this
